
services:
  db:
    image: postgres:16-alpine # Imagen ligera y estable
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Almacenamiento persistente para que los datos no se pierdan al detener el contenedor
      - postgres_data:/var/lib/postgresql/data/
    ports:
      # Exponer el puerto de Postgres (opcional, pero útil para herramientas externas)
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_service:
    build: .
    command: python auth_process.py
    restart: always
    volumes:
      - .:/app
    ports:
      - "9998:9998"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}

  analyzer_service:
    build: .
    command: python server.py
    restart: always
    volumes:
      - .:/app
    ports:
      - "9999:9999"
    depends_on:
      db:
        condition: service_healthy

  # --- Servicio de tu Aplicación Flask ---
  web:
    build: . # Le indica que construya desde el Dockerfile en el directorio actual
    command: bash -c "flask init-db && flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    volumes:
      - .:/app # Monta el código fuente
    depends_on:
      db:
        condition: service_healthy
      auth_service:
        condition: service_started
      analyzer_service:
        condition: service_started
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      FLASK_APP: app.app
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}

volumes:
  postgres_data: